services:
  - type: web
    name: terra-kitchen-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://restaurant-website-pvz6.onrender.com
      - key: PORT
        value: "5000"
    staticPublicPath: public
    autoDeploy: true
    buildCache: npm
